### ISSUE TITLE
Add option for on premise

### ISSUE THREAD

**Issue by jessielaf** [mcalpinefree/terraform-provider-plausible#22]
Hi there,

Thank you for creating this plugin! I have installed plausible on my own server. I see that plausible.io is hardcoded.

Maybe it is a possibility to add `url`/`address`/`domain` as an option for the provider! Like such:

```
provider "plausible" {
  username = "admin"
  password = "admin"
  url = 'plausible.example.com'
}
```

I don't know GO and are not familiar with creating terraform modules. Otherwise I would've done it myself.

**Comment by kurtmc** [comment]
@jessielaf Thanks for submitting this issue. I am sure I can sort something out so that the URL is configurable.
