### ISSUE TITLE
V1: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by briananstett** [mcalpinefree/terraform-provider-plausible#26]
I'm having some issues creating `plausible_site` resource after the new v1 update.

### Terraform Version
`v1.2.7`

### Affected Resource(s)
Please list the resources as a list, for example:
- `plausible_site`

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    plausible = {
      source  = "mcalpinefree/plausible"
      version = "1.0.0"
    }
  }
  required_version = "~> 1.0"
}

provider "plausible" {
}

resource "plausible_site" "this" {
  domain   = "google.com"
  timezone = "US/Eastern"
}
```

### Expected Behavior
Created Plausible Site resource

### Actual Behavior
```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to plausible_site.fe[0], provider
│ "provider[\"registry.terraform.io/mcalpinefree/plausible\"]" produced an unexpected new value: Root resource was
│ present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by kurtmc** [comment]
Hi @briananstett ! Thanks for the bug report!

I tested this out and I get the same issue, under further investigation it looks like Plausible will not allow multiple people to register the same domain or have the same domain registered multiple times in their own account.

Having said that, the error you get back from terraform is not helpful in identifying the underlying issue so I have made an improvement to print out the error message returned by the API. If you upgrade to the new version v1.0.1 you will see the following error message now:

```
plausible_site.this: Creating...
╷
│ Error: error creating site (google.com): could not create site: {"error":"domain This domain has already been taken. Perhaps one of your team members registered it? If that's not the case, please contact support@plausible.io"}
│ 
│   with plausible_site.this,
│   on main.tf line 14, in resource "plausible_site" "this":
│   14: resource "plausible_site" "this" {
│ 
╵
```

I suggest that you take a look at your Plausible account and check if the domain has already been registered, if you already have it in there and want to manage it with terraform you should be able to import it into the state using the command like this:

```
terraform import plausible_site.this google.com
```
