### ISSUE TITLE
Add custom domain

### ISSUE THREAD

**Issue by kurtmc** [mcalpinefree/terraform-provider-plausible#5]
Possible design:
```terraform
resource "plausible_site" "github" {
  domain = "github.com"
  timezone = "Pacific/Auckland"
}

resource "plausible_custom_domain" {
  site_id  = plausible_site.github.id
  domain = "stats.github.com"
}
```

this resource should also output an attribute named `cname` with the value `custom.plausible.io.` and `javascript_snippet` with value `<script async defer data-domain="github.com" src="https://stats.github.com/js/index.js"></script>`

**Comment by binaryfire** [comment]
Hey @kurtmc, sorry if this is a bit off topic but just wondering how your provider works... Are you adding / deleting sites directly in the PostgreSQL db?

I'm looking to achieve the same result as your provider using bash scripts and automation.

**Comment by kurtmc** [comment]
@binaryfire I am actually doing it all via http. Right now there isn't an official api to create and delete sites but I believe  they will be adding it soon. Once that is done I will switch over to using a proper api.

**Comment by kurtmc** [comment]
This is not required now, see: https://plausible.io/docs/proxy/introduction
